name: QA Release
on:
  push:
    branches: ["release/qa"]
permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write
jobs:
  release:
    name: Release
    uses: ./.github/workflows/deploy.yml
    with:
      environment: qa
    secrets: inherit
